export const copy = {
  appName: "نسب",
  tagline: "شجرة العائلة",
  tree: "الشجرة",
  houses: "البيوت",
  fan: "المروحة",
  addChild: "إضافة أبناء",
  addSon: "ابن",
  addDaughter: "ابنة",
  addBrother: "أخ",
  addSister: "أخت",
  addSonFull: "إضافة ابن",
  addDaughterFull: "إضافة ابنة",
  addBrotherFull: "إضافة أخ",
  addSisterFull: "إضافة أخت",
  addSpouse: "إضافة زوج / زوجة",
  addAnotherSpouse: "زوجة أخرى",
  addHusband: "زوج",
  currentWives: "الزوجات",
  willBeWife: (rank: string) => `ستُضاف كـ الزوجة ${rank} من أربع`,
  firstWifeHint: "لا زوجة مسجّلة بعد — ستُضاف كـ الزوجة الأولى",
  maxWives: "أربع زوجات حاليات حدّاً أقصى. السابقات والمتوفيات يُذكرن ولا يُحسبن ضمن الأربع.",
  maxWivesReached: "اكتملت أربع زوجات حاليات. يمكنك إضافة زوجة سابقة أو متوفاة.",
  currentWife: "زوجة حالية",
  previousWife: "زوجة سابقة",
  previousDeceasedWife: "زوجة متوفاة",
  previousWifeHint: "زوجة سابقة تبقى أمّاً لأبنائها في الشجرة.",
  previousDeceasedHint: "تبقى أمّاً لأبنائها. أدخل تاريخ الوفاة إن عُلم.",
  wifeKind: "صفة الزوجية",
  moreWifeOptions: "سابقة أو متوفاة؟ إظهار عند الحاجة",
  hideWifeOptions: "إخفاء",
  sonFromWife: "هذا الابن من أي زوجة؟",
  daughterFromWife: "هذه الابنة من أي زوجة؟",
  wifePickerHint: "يُربط الابن بأمه في الشجرة حسب الزوجة المختارة.",
  noWifeYet: "لا توجد زوجة مسجّلة — أضف زوجة أولاً لربط الأبناء بها.",
  addFather: "إضافة أب",
  addMother: "إضافة أم",
  addPerson: "إضافة شخص",
  edit: "تعديل",
  save: "حفظ",
  cancel: "إلغاء",
  delete: "حذف",
  finishAdding: "إنهاء الإضافة",
  saveAndNext: "حفظ وإضافة آخر",
  makeFocus: "محور الشجرة",
  people: "الأشخاص",
  saves: "النسخ المحفوظة",
  search: "بحث بالاسم",
  givenName: "الاسم",
  fatherName: "اسم الأب",
  familyName: "العائلة",
  houseHead: "رأس بيت",
  houseHeadHint: "لوحة تحت البطاقة تميّزه كجدّ هذه العائلة.",
  gender: "الجنس",
  male: "ذكر",
  female: "أنثى",
  genderUnknown: "غير محدد",
  birthDate: "تاريخ الميلاد",
  birthPlace: "مكان الميلاد",
  deathDate: "تاريخ الوفاة",
  deathPlace: "مكان الوفاة",
  residence: "مكان الإقامة",
  occupation: "المهنة",
  notes: "ملاحظات",
  country: "البلد",
  countryNone: "غير محدد",
  burialPlace: "مكان الدفن",
  burialGps: "رابط أو إحداثيات الموقع",
  burialGpsHint: "رابط خرائط، أو رقمين مثل 29.31, 47.88",
  openMap: "فتح الموقع على الخريطة",
  optionalFields: "حقول إضافية (اختياري)",
  showOptional: "إظهار عند الحاجة فقط",
  hideOptional: "إخفاء",
  photoSize: "حجم الصورة",
  photoSmall: "صغير",
  photoMedium: "وسط",
  photoLarge: "كبير",
  photoZoom: "تصغير / تكبير داخل الإطار",
  dragPhoto: "اسحب الصورة داخل الإطار لاختيار الوجه",
  viewFile: "عرض",
  closePreview: "إغلاق المعاينة",
  photo: "الصورة الشخصية",
  changePhoto: "تغيير الصورة",
  documents: "المستندات",
  birthCert: "شهادة الميلاد",
  deathCert: "شهادة الوفاة",
  otherDoc: "مستند آخر",
  docTitle: "اسم المستند",
  renameDoc: "تسمية",
  docPresets: ["شهادة ميلاد", "شهادة دراسية", "شهادة وفاة", "صورة قبر", "مستند آخر"],
  addFile: "إرفاق",
  noDocs: "لا توجد مستندات بعد",
  fileTooBig: "الملف أكبر من الحد المسموح (٨ ميغابايت)",
  fileSaved: "تم إرفاق الملف",
  photoSaved: "تم حفظ الصورة",
  otherParent: "هذا الابن من",
  none: "بدون زوج مسجّل",
  required: "هذا الحقل مطلوب",
  living: "على قيد الحياة",
  deceased: "متوفى",
  children: "الأبناء",
  childrenFrom: "أبناؤها من",
  parents: "الوالدان",
  spouse: "الزوج / الزوجة",
  wives: "الزوجات",
  kin: "إضافة قرابة",
  similarNames: "أسماء مشابهة في الشجرة",
  similarHint: "اختياري — للتفريق بين الأسماء المتشابهة، الوالدة هي الفيصل.",
  useExisting: "استخدام الموجود",
  linkedExisting: "رُبط الشخص الموجود دون تكرار",
  alreadyInTree: "هذا الاسم موجود",
  camera: "الكاميرا",
  fromLibrary: "من الصور",
  personPhoto: "صورة الشخص",
  details: "التفاصيل",
  personFile: "ملف الشخص",
  openFile: "الملف",
  doubleClickHint: "نقرة على الاسم تفتح الملف — الإضافة والحذف من داخله.",
  unknown: "غير معروف",
  yearOnlyHint: "يمكن ترك اليوم فارغاً عبر اختيار أول يوم في السنة",
  bindUnavailable: "تم تنزيل نسب-حالية.json — من نافذة التنزيل احفظه على الفلاش أو في المستندات.",
  downloadToUsb: "تم تنزيل نسب-حالية.json — احفظه على الفلاش أو انقله من مجلد التنزيلات.",
  restoreDone: "تمت استعادة النسخة",
  importDone: "تم استيراد الشجرة",
  exportDone: "تم تنزيل ملف الشجرة",
  selectPerson: "اختر شخصاً من الشجرة",
  close: "إغلاق",
  confirmNew: "سيتم استبدال الشجرة الحالية بشجرة فارغة. النسخ المحفوظة تبقى في السجل.",
  confirmDelete: "سيتم حذف هذا الشخص من الشجرة. النسخ المحفوظة تبقى.",
  newTreeTitle: "شجرة جديدة",
  firstPerson: "الشخص الأول",
  create: "إنشاء",
  zoomIn: "تكبير",
  zoomOut: "تصغير",
  fit: "ملاءمة",
  undo: "تراجع",
  redo: "إعادة",
  share: "مشاركة",
  familyForm: "نموذج تعبئة",
  familyFormHint: "أرسل هذا النموذج لفرد العائلة ليملأ بياناته ثم نُدخلها في الشجرة.",
  copied: "نُسخ ملف JSON إلى الحافظة",
  bornAbbr: "و.",
  diedAbbr: "ت.",
  houseOf: "بيت",
  noHouses: "لا توجد بيوت بعد — أضف زوجين أو أبناء لتشكيل بيت.",
  generations: "أجيال",
  personCount: "شخص",
  lastEdited: "آخر تعديل",
  noSaves: "لا توجد نسخ محفوظة بعد",
  noPeople: "لا يوجد أشخاص",
  demoBanner: "فرع أولي من مخطط شجرة الحمراني — راجعه وأكمله، أو ابدأ من جديد",
  startNew: "ابدأ من جديد",
  dismiss: "متابعة التعديل",
  emptyTree: "ابدأ بإضافة الشخص الأول في الشجرة",
  autoSaved: "حُفظ تلقائياً",
  saveFile: "حفظ",
  saveAs: "حفظ ملف الأنساب",
  fileName: "اسم الملف",
  chooseWhere: "GEDCOM 5.5.1 — اختر المجلد من نافذة النظام إن ظهرت.",
  draftHint: "إن لم تظهر نافذة المجلد، المعاينة تمنعها. بعد Publish في كروم تظهر نافذة المستندات.",
  copyGed: "حفظ واختر المجلد",
  downloadGed: "تنزيل GEDCOM",
  importFromUsb: "استيراد GEDCOM",
  openExistingHint: "فتح ملف ‎.ged من جهازك.",
  savedPicked: "حُفظ في المجلد الذي اخترته.",
  browserOnly: "سجل هذه الجلسة داخل المتصفح — ليس ملفات على الجهاز",
  savedAs: (name: string) => `تم حفظ: ${name}`,
  unsaved: "غير محفوظ",
  bindFolder: "اختيار مجلد الحفظ",
  chooseUsb: "اختيار فلاش أو مجلد",
  folderBound: "المجلد مربوط",
  folderNameLabel: (name: string) => `مكان الحفظ: ${name}`,
  noFolderYet: "لم يُحدَّد مجلد بعد",
  latestFileHint: "الملف الدائم داخل المجلد اسمه نسب-حالية.json — انسخه أو افتحه من جهاز آخر.",
  unbindFolder: "إلغاء ربط المجلد",
  workElsewhere: "للعمل من مكان آخر",
  folderHelp: "اختر مجلدًا على الفلاش أو في المستندات. كل حفظ يكتب ملف نسب-حالية.ged داخله.",
  exportJson: "تنزيل الملف",
  importJson: "فتح ملف",
  restoreSave: "استعادة",
  downloadSave: "تنزيل",
  childSaved: (name: string) => `حُفظ ${name}`,
  addedCount: (n: number) => (n ? `أُضيف ${n} — أضف ابناً أو ابنة دون إغلاق` : "أدخل بيانات الابن الأول ثم احفظ لإضافة التالي"),
  fatherOf: "والده",
  motherOf: "والدته",
} as const;
