import type { Person, TreeData } from "./types";

function p(
  partial: Omit<
    Person,
    "countryCode" | "photoId" | "photoScale" | "photoSize" | "photoX" | "photoY" | "houseHead" | "wifeKind" | "burialPlace" | "burialGps" | "documents" | "spouseIds" | "grandfatherName" | "greatGrandfatherName" | "kunya" | "deceased" | "birthOrder"
  > &
    Partial<Person>,
): Person {
  const spouseIds = partial.spouseIds ?? (partial.spouseId ? [partial.spouseId] : []);
  return {
    countryCode: "KW",
    photoId: null,
    burialPlace: "",
    burialGps: "",
    documents: [],
    grandfatherName: partial.grandfatherName ?? "",
    greatGrandfatherName: partial.greatGrandfatherName ?? "",
    kunya: partial.kunya ?? "",
    deceased: partial.deceased ?? Boolean(partial.deathDate),
    birthOrder: partial.birthOrder ?? 0,
    ...partial,
    photoScale: partial.photoScale ?? 1,
    photoSize: partial.photoSize ?? "md",
    photoX: partial.photoX ?? 50,
    photoY: partial.photoY ?? 50,
    houseHead: partial.houseHead ?? false,
    wifeKind: partial.wifeKind ?? (partial.deathDate ? "deceased" : "current"),
    spouseIds,
  };
}

export const DEMO_FOCUS_ID = "mohammed-khaled";

export function createDemoTree(): TreeData {
  const people: Record<string, Person> = {
    "hamad-salem": p({
      id: "hamad-salem",
      givenName: "حمد",
      fatherName: "سالم",
      familyName: "المنصور",
      gender: "male",
      birthDate: "1924-01-17",
      birthPlace: "مدينة الكويت",
      deathDate: "2001-05-04",
      deathPlace: "مدينة الكويت",
      burialPlace: "مقبرة الصليبيخات",
      burialGps: "29.318,47.885",
      residence: "مدينة الكويت",
      occupation: "",
      notes: "",
      fatherId: null,
      motherId: null,
      spouseId: "maryam-nayef",
      houseHead: true,
    }),
    "maryam-nayef": p({
      id: "maryam-nayef",
      givenName: "مريم",
      fatherName: "نايف",
      familyName: "العنزي",
      gender: "female",
      birthDate: "1928-07-14",
      birthPlace: "الجهراء",
      deathDate: "2015-03-19",
      deathPlace: "مدينة الكويت",
      burialPlace: "مقبرة الصليبيخات",
      burialGps: "29.318,47.885",
      residence: "مدينة الكويت",
      occupation: "",
      notes: "",
      fatherId: null,
      motherId: null,
      spouseId: "hamad-salem",
    }),
    "khaled-hamad": p({
      id: "khaled-hamad",
      givenName: "خالد",
      fatherName: "حمد",
      familyName: "المنصور",
      gender: "male",
      birthDate: "1952-04-08",
      birthPlace: "مدينة الكويت",
      deathDate: "",
      deathPlace: "",
      residence: "مدينة الكويت",
      occupation: "",
      notes: "",
      fatherId: "hamad-salem",
      motherId: "maryam-nayef",
      spouseId: "sarah-jassim",
    }),
    "jassim-ali": p({
      id: "jassim-ali",
      givenName: "جاسم",
      fatherName: "علي",
      familyName: "العلي",
      gender: "male",
      birthDate: "1929-01-05",
      birthPlace: "حولى",
      deathDate: "2005-12-11",
      deathPlace: "حولى",
      residence: "حولى",
      occupation: "",
      notes: "",
      fatherId: null,
      motherId: null,
      spouseId: "latifa-saad",
    }),
    "latifa-saad": p({
      id: "latifa-saad",
      givenName: "لطيفة",
      fatherName: "سعد",
      familyName: "الرويعي",
      gender: "female",
      birthDate: "1933-08-27",
      birthPlace: "مدينة الكويت",
      deathDate: "2019-04-03",
      deathPlace: "حولى",
      residence: "حولى",
      occupation: "",
      notes: "",
      fatherId: null,
      motherId: null,
      spouseId: "jassim-ali",
    }),
    "sarah-jassim": p({
      id: "sarah-jassim",
      givenName: "سارة",
      fatherName: "جاسم",
      familyName: "العلي",
      gender: "female",
      birthDate: "1956-06-19",
      birthPlace: "حولى",
      deathDate: "",
      deathPlace: "",
      residence: "مدينة الكويت",
      occupation: "",
      notes: "",
      fatherId: "jassim-ali",
      motherId: "latifa-saad",
      spouseId: "khaled-hamad",
    }),
    "mohammed-khaled": p({
      id: "mohammed-khaled",
      givenName: "محمد",
      fatherName: "خالد",
      familyName: "المنصور",
      gender: "male",
      birthDate: "1980-03-14",
      birthPlace: "مدينة الكويت",
      deathDate: "",
      deathPlace: "",
      residence: "مدينة الكويت",
      occupation: "",
      notes: "",
      fatherId: "khaled-hamad",
      motherId: "sarah-jassim",
      spouseId: "nouf-meshaal",
    }),
    "sabah-meshaal": p({
      id: "sabah-meshaal",
      givenName: "صباح",
      fatherName: "مشعل",
      familyName: "الصباح",
      gender: "male",
      birthDate: "1928-01-01",
      birthPlace: "مدينة الكويت",
      deathDate: "2004-07-23",
      deathPlace: "مدينة الكويت",
      residence: "مدينة الكويت",
      occupation: "",
      notes: "",
      fatherId: null,
      motherId: null,
      spouseId: "mouza-salem",
    }),
    "mouza-salem": p({
      id: "mouza-salem",
      givenName: "موزة",
      fatherName: "سالم",
      familyName: "السالم",
      gender: "female",
      birthDate: "1932-01-01",
      birthPlace: "مدينة الكويت",
      deathDate: "2011-10-05",
      deathPlace: "مدينة الكويت",
      residence: "مدينة الكويت",
      occupation: "",
      notes: "",
      fatherId: null,
      motherId: null,
      spouseId: "sabah-meshaal",
    }),
    "meshaal-sabah": p({
      id: "meshaal-sabah",
      givenName: "مشعل",
      fatherName: "صباح",
      familyName: "الصباح",
      gender: "male",
      birthDate: "1955-02-18",
      birthPlace: "مدينة الكويت",
      deathDate: "",
      deathPlace: "",
      residence: "مدينة الكويت",
      occupation: "",
      notes: "",
      fatherId: "sabah-meshaal",
      motherId: "mouza-salem",
      spouseId: null,
    }),
    "nouf-meshaal": p({
      id: "nouf-meshaal",
      givenName: "نوف",
      fatherName: "مشعل",
      familyName: "الصباح",
      gender: "female",
      birthDate: "1983-05-18",
      birthPlace: "مدينة الكويت",
      deathDate: "",
      deathPlace: "",
      residence: "مدينة الكويت",
      occupation: "",
      notes: "",
      fatherId: "meshaal-sabah",
      motherId: null,
      spouseId: "mohammed-khaled",
    }),
    "mansour-mohammed": p({
      id: "mansour-mohammed",
      givenName: "منصور",
      fatherName: "محمد",
      familyName: "المنصور",
      gender: "male",
      birthDate: "2008-01-19",
      birthPlace: "مدينة الكويت",
      deathDate: "",
      deathPlace: "",
      residence: "مدينة الكويت",
      occupation: "",
      notes: "",
      fatherId: "mohammed-khaled",
      motherId: "nouf-meshaal",
      spouseId: null,
    }),
    "jawaher-mohammed": p({
      id: "jawaher-mohammed",
      givenName: "جواهر",
      fatherName: "محمد",
      familyName: "المنصور",
      gender: "female",
      birthDate: "2011-08-04",
      birthPlace: "مدينة الكويت",
      deathDate: "",
      deathPlace: "",
      residence: "مدينة الكويت",
      occupation: "",
      notes: "",
      fatherId: "mohammed-khaled",
      motherId: "nouf-meshaal",
      spouseId: null,
    }),
    "salem-mohammed": p({
      id: "salem-mohammed",
      givenName: "سالم",
      fatherName: "محمد",
      familyName: "المنصور",
      gender: "male",
      birthDate: "2015-11-11",
      birthPlace: "مدينة الكويت",
      deathDate: "",
      deathPlace: "",
      residence: "مدينة الكويت",
      occupation: "",
      notes: "",
      fatherId: "mohammed-khaled",
      motherId: "nouf-meshaal",
      spouseId: null,
    }),
  };

  return {
    version: 1,
    treeName: "آل المنصور",
    people,
    focusId: DEMO_FOCUS_ID,
    updatedAt: "2026-08-29T18:43:00.000Z",
  };
}

export function isStockDemo(data: { people?: Record<string, Person> } | null | undefined): boolean {
  if (!data?.people) return true;
  const ids = Object.keys(data.people);
  if (!ids.length) return true;
  const demoIds = Object.keys(createDemoTree().people);
  if (ids.length !== demoIds.length) return false;
  return demoIds.every((id) => id in data.people!);
}
